# pyright: reportMissingImports=false
"""
SQLAlchemy models for agent types and agent instances.

This module defines the database schema for agent management,
including agent type definitions and runtime agent instances.
"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import TYPE_CHECKING, Any, Optional
from uuid import UUID

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    Column,
    DateTime,
    ForeignKey,
    Index,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID as PostgreSQLUUID
from sqlalchemy.orm import Mapped, relationship, mapped_column

from db.base import Base
from db.types import AgentStatus

if TYPE_CHECKING:
    from db.schema.users import User
    from db.schema.tasks import Task
    from db.schema.task_queue import TaskQueue
    from db.schema.collaboration import CollaborationSession, AgentMessage
    from db.schema.token_usage import TokenUsage


def gen_random_uuid() -> UUID:
    """Generate a random UUID v4 for database default."""
    import uuid
    return uuid.uuid4()


def now_utc() -> datetime:
    """Get current UTC datetime."""
    return datetime.now(timezone.utc)


class AgentType(Base):
    """Agent type definition model.
    
    This table stores reusable agent type definitions with their
    capabilities and default configurations.
    """
    
    __tablename__ = "agent_types"
    
    id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        primary_key=True,
        default=gen_random_uuid,
        server_default=func.gen_random_uuid(),
    )
    """Primary key - UUID v4 generated by PostgreSQL."""
    
    name: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        unique=True,
        index=True,
    )
    """Unique name for the agent type."""
    
    description: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
    )
    """Human-readable description of the agent type."""
    
    capabilities: Mapped[Optional[dict[str, Any]]] = mapped_column(
        JSONB,
        nullable=True,
    )
    """JSONB field storing agent capabilities as key-value pairs."""
    
    default_config: Mapped[Optional[dict[str, Any]]] = mapped_column(
        JSONB,
        nullable=True,
    )
    """JSONB field storing default configuration for this agent type."""
    
    is_active: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=True,
        server_default="true",
    )
    """Whether the agent type is currently active and available."""
    
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=now_utc,
        server_default=func.now(),
    )
    """Record creation timestamp (UTC)."""
    
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=now_utc,
        server_default=func.now(),
        onupdate=now_utc,
    )
    """Last update timestamp (UTC)."""
    
    # Relationship to agent instances
    instances: Mapped[list["AgentInstance"]] = relationship(
        "AgentInstance",
        back_populates="agent_type",
        cascade="all, delete-orphan",
    )
    """Agent instances of this type."""
    
    __table_args__ = (
        UniqueConstraint("name", name="uq_agent_types_name"),
        Index("idx_agent_types_is_active", "is_active"),
    )
    
    def __repr__(self) -> str:
        return f"<AgentType(id={self.id}, name={self.name!r}, is_active={self.is_active})>"


class AgentInstance(Base):
    """Agent instance model.
    
    This table stores runtime instances of agents, tracking their
    status, configuration, and association with users.
    """
    
    __tablename__ = "agent_instances"
    
    id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        primary_key=True,
        default=gen_random_uuid,
        server_default=func.gen_random_uuid(),
    )
    """Primary key - UUID v4 generated by PostgreSQL."""
    
    agent_type_id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        ForeignKey("agent_types.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    """Foreign key reference to the agent type."""
    
    user_id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=False,  # We'll create a custom index below
    )
    """Foreign key reference to the owning user."""
    
    name: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
    )
    """Optional human-readable name for this instance."""
    
    status: Mapped[AgentStatus] = mapped_column(
        String(50),
        nullable=False,
        default=AgentStatus.idle,
        server_default=AgentStatus.idle.value,
    )
    """Current operational status of the agent instance."""
    
    config: Mapped[Optional[dict[str, Any]]] = mapped_column(
        JSONB,
        nullable=True,
    )
    """JSONB field storing instance-specific configuration overrides."""
    
    last_heartbeat_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )
    """Last heartbeat timestamp for liveness detection."""
    
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=now_utc,
        server_default=func.now(),
    )
    """Record creation timestamp (UTC)."""
    
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=now_utc,
        server_default=func.now(),
        onupdate=now_utc,
    )
    """Last update timestamp (UTC)."""
    
    # Relationships
    agent_type: Mapped["AgentType"] = relationship(
        "AgentType",
        back_populates="instances",
    )
    """The agent type this instance is based on."""
    
    user: Mapped["User"] = relationship(
        "User",
        back_populates="agent_instances",
    )
    """The user who owns this agent instance."""
    
    # Relationship to tasks
    tasks: Mapped[list["Task"]] = relationship(
        back_populates="agent",
    )
    """Tasks assigned to this agent instance."""
    
    claimed_tasks: Mapped[list["TaskQueue"]] = relationship(
        back_populates="claiming_agent",
    )
    """Queue entries claimed by this agent instance."""
    
    collaboration_sessions: Mapped[list["CollaborationSession"]] = relationship(
        back_populates="main_agent",
    )
    """Collaboration sessions coordinated by this agent."""
    
    sent_messages: Mapped[list["AgentMessage"]] = relationship(
        foreign_keys="AgentMessage.sender_agent_id",
        back_populates="sender_agent",
    )
    """Messages sent by this agent."""
    
    received_messages: Mapped[list["AgentMessage"]] = relationship(
        foreign_keys="AgentMessage.receiver_agent_id",
        back_populates="receiver_agent",
    )
    """Messages received by this agent."""
    
    # Relationship to token usage
    token_usages: Mapped[list["TokenUsage"]] = relationship(
        "TokenUsage",
        back_populates="agent",
        cascade="all, delete-orphan",
    )
    """Token usage records for this agent instance."""
    
    __table_args__ = (
        CheckConstraint(
            "status IN ('idle', 'busy', 'error', 'offline')",
            name="ck_agent_instances_status",
        ),
        Index("idx_agent_instances_status", "status"),
        Index("idx_agent_instances_user", "user_id"),
    )
    
    def __repr__(self) -> str:
        return f"<AgentInstance(id={self.id}, agent_type_id={self.agent_type_id}, user_id={self.user_id}, status={self.status!r})>"
