# pyright: reportMissingImports=false
"""
SQLAlchemy model for agent capabilities.

This module defines the database schema for agent capability definitions,
including input/output schemas and capability metadata.
"""
from __future__ import annotations

from datetime import datetime
from typing import Any, Optional
from uuid import UUID

from sqlalchemy import (
    Boolean,
    DateTime,
    ForeignKey,
    Index,
    Text,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID as PostgreSQLUUID
from sqlalchemy.orm import Mapped, mapped_column

from db.base import Base
from db.schema.agents import gen_random_uuid, now_utc


class AgentCapability(Base):
    """Agent capability definition model.
    
    This table stores reusable capability definitions that can be
    associated with agent types. Each capability includes input/output
    schema definitions for validation.
    """
    
    __tablename__ = "agent_capabilities"
    
    id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        primary_key=True,
        default=gen_random_uuid,
        server_default=func.gen_random_uuid(),
    )
    """Primary key - UUID v4 generated by PostgreSQL."""
    
    agent_type_id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        ForeignKey("agent_types.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    """Foreign key reference to the agent type that owns this capability."""
    
    capability_name: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        index=True,
    )
    """Name of the capability."""
    
    description: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
    )
    """Human-readable description of the capability."""
    
    input_schema: Mapped[Optional[dict[str, Any]]] = mapped_column(
        JSONB,
        nullable=True,
    )
    """JSONB field storing JSON Schema definition for input validation."""
    
    output_schema: Mapped[Optional[dict[str, Any]]] = mapped_column(
        JSONB,
        nullable=True,
    )
    """JSONB field storing JSON Schema definition for output validation."""
    
    is_active: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=True,
        server_default="true",
    )
    """Whether the capability is currently active and available."""
    
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=now_utc,
        server_default=func.now(),
    )
    """Record creation timestamp (UTC)."""
    
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=now_utc,
        server_default=func.now(),
        onupdate=now_utc,
    )
    """Last update timestamp (UTC)."""
    
    __table_args__ = (
        Index("idx_capabilities_type", "agent_type_id"),
        Index("idx_capabilities_name", "capability_name"),
    )
    
    def __repr__(self) -> str:
        return f"<AgentCapability(id={self.id}, agent_type_id={self.agent_type_id}, capability_name={self.capability_name!r}, is_active={self.is_active})>"
