# pyright: reportMissingImports=false
"""
SQLAlchemy models for collaboration sessions and agent messages.

This module defines the database schema for multi-agent collaboration,
including session management and inter-agent message tracking.
"""
from __future__ import annotations

from datetime import datetime, timezone
from enum import StrEnum
from typing import TYPE_CHECKING, Any, Optional
from uuid import UUID

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    Column,
    DateTime,
    ForeignKey,
    Index,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID as PostgreSQLUUID
from sqlalchemy.orm import Mapped, relationship, mapped_column

from db.base import Base

if TYPE_CHECKING:
    from db.schema.agents import AgentInstance
    from db.schema.users import User


class CollaborationStatus(StrEnum):
    """
    Status of a collaboration session.
    
    Tracks the lifecycle state of collaborative agent sessions.
    String values ensure proper JSON serialization.
    """

    active = "active"
    """Session is currently active and ongoing."""

    completed = "completed"
    """Session finished successfully."""

    failed = "failed"
    """Session ended due to an error."""

    cancelled = "cancelled"
    """Session was cancelled before completion."""


class MessageRedactionLevel(StrEnum):
    """
    Redaction level for agent messages.
    
    Defines how much content is visible/redacted in messages.
    String values ensure proper JSON serialization.
    """

    none = "none"
    """No redaction - full content visible."""

    partial = "partial"
    """Partial redaction - some content hidden."""

    full = "full"
    """Full redaction - content completely hidden."""


class MessageType(StrEnum):
    """
    Type of agent message.
    
    Defines the nature of messages exchanged between agents.
    String values ensure proper JSON serialization.
    """

    request = "request"
    """Request for action or information."""

    response = "response"
    """Response to a request."""

    notification = "notification"
    """One-way notification without expected response."""

    ack = "ack"
    """Acknowledgment of received message."""

    tool_call = "tool_call"
    """Invocation of a tool/capability."""

    tool_result = "tool_result"
    """Result from a tool/capability execution."""


def gen_random_uuid() -> UUID:
    """Generate a random UUID v4 for database default."""
    import uuid
    return uuid.uuid4()


def now_utc() -> datetime:
    """Get current UTC datetime."""
    return datetime.now(timezone.utc)


class CollaborationSession(Base):
    """Collaboration session model.
    
    This table stores multi-agent collaboration sessions, tracking
    which agents are collaborating and the shared context.
    """
    
    __tablename__ = "collaboration_sessions"
    
    id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        primary_key=True,
        default=gen_random_uuid,
        server_default=func.gen_random_uuid(),
    )
    """Primary key - UUID v4 generated by PostgreSQL."""
    
    user_id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    """Foreign key reference to the owning user."""
    
    main_agent_id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        ForeignKey("agent_instances.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    """Foreign key reference to the main coordinating agent instance."""
    
    name: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
    )
    """Optional human-readable name for the collaboration session."""
    
    session_id: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        unique=True,
    )
    """Unique session identifier with prefixes (session-{uuid}, default-{uuid}, ghost-{uuid}, refl-{uuid})."""
    
    status: Mapped[CollaborationStatus] = mapped_column(
        String(50),
        nullable=False,
        default=CollaborationStatus.active,
        server_default=CollaborationStatus.active.value,
    )
    """Current status of the collaboration session."""
    
    involves_secrets: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=False,
        server_default="false",
    )
    """Whether this collaboration involves sensitive/secrets data."""
    
    context_json: Mapped[Optional[dict[str, Any]]] = mapped_column(
        JSONB,
        nullable=True,
    )
    """JSONB field storing shared session context as key-value pairs."""
    
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=now_utc,
        server_default=func.now(),
    )
    """Record creation timestamp (UTC)."""
    
    ended_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )
    """Session end timestamp (UTC)."""
    
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=now_utc,
        server_default=func.now(),
        onupdate=now_utc,
    )
    """Last update timestamp (UTC)."""
    
    # Relationships
    user: Mapped["User"] = relationship(
        "User",
        back_populates="collaboration_sessions",
    )
    """The user who owns this collaboration session."""
    
    main_agent: Mapped["AgentInstance"] = relationship(
        "AgentInstance",
        back_populates="collaboration_sessions",
    )
    """The main agent coordinating this collaboration."""
    
    messages: Mapped[list["AgentMessage"]] = relationship(
        "AgentMessage",
        back_populates="collaboration",
        cascade="all, delete-orphan",
    )
    """Messages exchanged within this collaboration session."""
    
    __table_args__ = (
        CheckConstraint(
            "status IN ('active', 'completed', 'failed', 'cancelled')",
            name="ck_collaboration_sessions_status",
        ),
        UniqueConstraint("session_id", name="uq_collaboration_sessions_session_id"),
        Index("idx_collab_user", "user_id"),
        Index("idx_collab_status", "status"),
    )
    
    def __repr__(self) -> str:
        return f"<CollaborationSession(id={self.id}, user_id={self.user_id}, status={self.status!r})>"


class AgentMessage(Base):
    """Agent message model.
    
    This table stores messages exchanged between agents during
    collaboration sessions, with step tracking for conversation flows.
    """
    
    __tablename__ = "agent_messages"
    
    id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        primary_key=True,
        default=gen_random_uuid,
        server_default=func.gen_random_uuid(),
    )
    """Primary key - UUID v4 generated by PostgreSQL."""
    
    collaboration_id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        ForeignKey("collaboration_sessions.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    """Foreign key reference to the collaboration session."""
    
    step_id: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
    )
    """Optional step identifier grouping related messages in an interaction flow."""
    
    sender_agent_id: Mapped[Optional[UUID]] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        ForeignKey("agent_instances.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    """Foreign key reference to the sending agent instance."""
    
    receiver_agent_id: Mapped[Optional[UUID]] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        ForeignKey("agent_instances.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    """Foreign key reference to the receiving agent instance."""
    
    message_type: Mapped[MessageType] = mapped_column(
        String(50),
        nullable=False,
        default=MessageType.request,
        server_default=MessageType.request.value,
    )
    """Type of the message (request/response/notification/ack/tool_call/tool_result)."""
    
    content_json: Mapped[dict[str, Any]] = mapped_column(
        JSONB,
        nullable=False,
    )
    """JSONB field storing structured message content."""
    
    redaction_level: Mapped[MessageRedactionLevel] = mapped_column(
        String(50),
        nullable=False,
        default=MessageRedactionLevel.none,
        server_default=MessageRedactionLevel.none.value,
    )
    """Redaction level for message content."""
    
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=now_utc,
        server_default=func.now(),
    )
    """Message creation timestamp (UTC)."""
    
    # Relationships
    collaboration: Mapped["CollaborationSession"] = relationship(
        "CollaborationSession",
        back_populates="messages",
    )
    """The collaboration session this message belongs to."""
    
    sender_agent: Mapped[Optional["AgentInstance"]] = relationship(
        "AgentInstance",
        foreign_keys=[sender_agent_id],
        back_populates="sent_messages",
    )
    """The agent that sent this message."""
    
    receiver_agent: Mapped[Optional["AgentInstance"]] = relationship(
        "AgentInstance",
        foreign_keys=[receiver_agent_id],
        back_populates="received_messages",
    )
    """The agent that received this message."""
    
    __table_args__ = (
        CheckConstraint(
            "message_type IN ('request', 'response', 'notification', 'ack', 'tool_call', 'tool_result')",
            name="ck_agent_messages_message_type",
        ),
        CheckConstraint(
            "redaction_level IN ('none', 'partial', 'full')",
            name="ck_agent_messages_redaction_level",
        ),
        Index("idx_messages_collab", "collaboration_id", "created_at"),
        Index("idx_messages_step", "step_id"),
    )
    
    def __repr__(self) -> str:
        return f"<AgentMessage(id={self.id}, collaboration_id={self.collaboration_id}, type={self.message_type!r})>"
