# pyright: reportMissingImports=false
"""
SQLAlchemy model for dead letter queue.

This module defines the database schema for dead letter queue management,
preserving failed task context for debugging and reprocessing.
"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import TYPE_CHECKING, Any, Optional
from uuid import UUID

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID as PostgreSQLUUID
from sqlalchemy.orm import Mapped, relationship, mapped_column

from db.base import Base
from db.types import TaskStatus

if TYPE_CHECKING:
    from db.schema.tasks import Task
    from db.schema.task_queue import TaskQueue
    from db.schema.users import User


def gen_random_uuid() -> UUID:
    """Generate a random UUID v4 for database default."""
    import uuid
    return uuid.uuid4()


def now_utc() -> datetime:
    """Get current UTC datetime."""
    return datetime.now(timezone.utc)


class DeadLetterQueue(Base):
    """Dead letter queue model for preserving failed task context.
    
    This table stores tasks/queue entries that have failed and been moved
    to the dead letter queue for administrative review. The DLQ preserves
    the full original context even if the original task record is deleted
    by retention policies.
    
    Key design decisions:
    - original_task_id uses SET NULL: allows task deletion without losing DLQ record
    - original_queue_entry_id uses CASCADE: queue entries are transient representation
    - original_payload_json preserves full context for potential reprocessing
    - failure_details_json stores full error context and stack traces
    - Resolution workflow includes audit trail (resolved_by, resolved_at)
    
    Critical partial indexes:
    - idx_dlq_unresolved: For monitoring active DLQ items (is_active = true)
    - idx_dlq_resolved: For historical review (resolved_at IS NOT NULL)
    """
    
    __tablename__ = "dead_letter_queue"
    
    id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        primary_key=True,
        default=gen_random_uuid,
        server_default=func.gen_random_uuid(),
    )
    """Primary key - UUID v4 generated by PostgreSQL."""
    
    original_task_id: Mapped[Optional[UUID]] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        ForeignKey("tasks.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    """Foreign key to original task (SET NULL on delete - preserves DLQ if task deleted)."""
    
    original_queue_entry_id: Mapped[Optional[UUID]] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        ForeignKey("task_queue.id", ondelete="CASCADE"),
        nullable=True,
        index=True,
    )
    """Foreign key to original queue entry (CASCADE - queue entries are transient)."""
    
    original_payload_json: Mapped[dict[str, Any]] = mapped_column(
        JSONB,
        nullable=False,
    )
    """JSONB field preserving full original record for debugging and reprocessing."""
    
    failure_reason: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )
    """Error type or classification (e.g., 'MaxRetriesExceeded', 'ValidationError')."""
    
    failure_details_json: Mapped[dict[str, Any]] = mapped_column(
        JSONB,
        nullable=False,
    )
    """JSONB field storing full error context, stack traces, and debugging information."""
    
    retry_count: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
        server_default="0",
    )
    """Number of times this item was moved to DLQ (for retry tracking)."""
    
    last_attempt_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )
    """Timestamp of the last failed execution attempt."""
    
    dead_lettered_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=now_utc,
        server_default=func.now(),
    )
    """When item was moved to dead letter queue."""
    
    resolved_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )
    """When admin marked this issue as resolved (NULL = unresolved)."""
    
    resolved_by: Mapped[Optional[UUID]] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    """Foreign key to user who resolved this (SET NULL allows user deletion without breaking DLQ)."""
    
    is_active: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=True,
        server_default="true",
    )
    """Whether this DLQ item is unresolved (True) or has been addressed (False)."""
    
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=now_utc,
        server_default=func.now(),
    )
    """Record creation timestamp (UTC)."""
    
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=now_utc,
        server_default=func.now(),
        onupdate=now_utc,
    )
    """Last update timestamp (UTC)."""
    
    # Relationships
    original_task: Mapped[Optional["Task"]] = relationship(
        back_populates="dlq_entries",
    )
    """The original task that failed (may be NULL if task was deleted)."""
    
    original_queue_entry: Mapped[Optional["TaskQueue"]] = relationship(
        back_populates="dlq_entries",
    )
    """The original queue entry that failed (may be NULL if queue entry was deleted)."""
    
    resolved_by_user: Mapped[Optional["User"]] = relationship(
        foreign_keys=[resolved_by],
    )
    """The user who resolved this DLQ entry (audit trail)."""
    
    __table_args__ = (
        CheckConstraint(
            "retry_count >= 0",
            name="ck_dead_letter_queue_retry_count",
        ),
        # Partial index for monitoring active/unresolved DLQ items
        # Most important for operational monitoring dashboards
        Index(
            "idx_dlq_unresolved",
            "created_at",
            postgresql_where=(is_active == True),
        ),
        # Partial index for resolved items (historical review and auditing)
        Index(
            "idx_dlq_resolved",
            "resolved_at",
            postgresql_where=(resolved_at.isnot(None)),
        ),
    )
    
    def __repr__(self) -> str:
        return f"<DeadLetterQueue(id={self.id}, original_task_id={self.original_task_id}, failure_reason={self.failure_reason!r}, is_active={self.is_active})>"
