# pyright: reportMissingImports=false
"""
SQLAlchemy models for tasks.

This module defines the database schema for task management,
including task tracking, scheduling, and parent-child task relationships.
"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import TYPE_CHECKING, Any, Optional
from uuid import UUID

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    Column,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID as PostgreSQLUUID
from sqlalchemy.orm import Mapped, relationship, mapped_column

from db.base import Base
from db.types import TaskStatus, Priority

if TYPE_CHECKING:
    from db.schema.users import User
    from db.schema.agents import AgentInstance
    from db.schema.task_schedules import TaskSchedule
    from db.schema.task_queue import TaskQueue
    from db.schema.dead_letter_queue import DeadLetterQueue
    from db.schema.tool_calls import ToolCall


def gen_random_uuid() -> UUID:
    """Generate a random UUID v4 for database default."""
    import uuid
    return uuid.uuid4()


def now_utc() -> datetime:
    """Get current UTC datetime."""
    return datetime.now(timezone.utc)


class Task(Base):
    """Task model for tracking agent tasks and their execution.
    
    This table stores task definitions, execution status, and results.
    Tasks can have parent-child relationships for hierarchical task decomposition.
    The session_id field links to LangGraph thread_id for checkpoint integration.
    """
    
    __tablename__ = "tasks"
    
    id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        primary_key=True,
        default=gen_random_uuid,
        server_default=func.gen_random_uuid(),
    )
    """Primary key - UUID v4 generated by PostgreSQL."""
    
    user_id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=False,  # We'll create a custom index below
    )
    """Foreign key reference to the owning user (CASCADE delete)."""
    
    agent_id: Mapped[Optional[UUID]] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        ForeignKey("agent_instances.id", ondelete="SET NULL"),
        nullable=True,
        index=False,  # We'll create a custom index below
    )
    """Foreign key reference to the executing agent instance (SET NULL on delete)."""
    
    session_id: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
    )
    """LangGraph thread_id for checkpoint integration and session tracking."""
    
    parent_task_id: Mapped[Optional[UUID]] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        ForeignKey("tasks.id", ondelete="CASCADE"),
        nullable=True,
        index=True,
    )
    """Self-referencing foreign key for parent-child task relationships (CASCADE delete)."""
    
    task_type: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )
    """Type of task (e.g., 'research', 'analysis', 'code_generation')."""
    
    status: Mapped[TaskStatus] = mapped_column(
        String(50),
        nullable=False,
        default=TaskStatus.pending,
        server_default=TaskStatus.pending.value,
    )
    """Current execution status of the task."""
    
    priority: Mapped[Priority] = mapped_column(
        String(50),
        nullable=False,
        default=Priority.normal,
        server_default=Priority.normal.value,
    )
    """Task priority level for scheduling."""
    
    payload: Mapped[Optional[dict[str, Any]]] = mapped_column(
        JSONB,
        nullable=True,
    )
    """JSONB field for task specifications and input parameters."""
    
    result: Mapped[Optional[dict[str, Any]]] = mapped_column(
        JSONB,
        nullable=True,
    )
    """JSONB field for task execution results and output."""
    
    error_message: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
    )
    """Error message if task execution failed."""
    
    retry_count: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
        server_default="0",
    )
    """Number of retry attempts made for this task."""
    
    max_retries: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=3,
        server_default="3",
    )
    """Maximum number of retry attempts allowed."""
    
    scheduled_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        index=True,
    )
    """Scheduled execution timestamp for temporal scheduling."""
    
    started_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )
    """Task execution start timestamp."""
    
    completed_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )
    """Task completion timestamp (success or failure)."""
    
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=now_utc,
        server_default=func.now(),
    )
    """Record creation timestamp (UTC)."""
    
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=now_utc,
        server_default=func.now(),
        onupdate=now_utc,
    )
    """Last update timestamp (UTC)."""
    
    # Relationships
    user: Mapped["User"] = relationship(
        back_populates="tasks",
    )
    """The user who owns this task."""
    
    agent: Mapped[Optional["AgentInstance"]] = relationship(
        back_populates="tasks",
    )
    """The agent instance executing this task."""
    
    parent_task: Mapped[Optional["Task"]] = relationship(
        "Task",
        remote_side="Task.id",
        back_populates="child_tasks",
        foreign_keys=[parent_task_id],
    )
    """Parent task in hierarchical decomposition."""
    
    child_tasks: Mapped[list["Task"]] = relationship(
        "Task",
        back_populates="parent_task",
        cascade="all, delete-orphan",
        foreign_keys=[parent_task_id],
    )
    """Child tasks in hierarchical decomposition."""
    
    schedule: Mapped[Optional["TaskSchedule"]] = relationship(
        back_populates="task_template",
    )
    """Schedule definition for this task template (if any)."""
    
    queue_entries: Mapped[list["TaskQueue"]] = relationship(
        back_populates="task",
        cascade="all, delete-orphan",
    )
    """Queue entries for this task (usually one, but supports multiple queue positions)."""
    
    dlq_entries: Mapped[list["DeadLetterQueue"]] = relationship(
        back_populates="original_task",
    )
    """Dead letter queue entries for this task (if any)."""
    
    tool_calls: Mapped[list["ToolCall"]] = relationship(
        back_populates="task",
        cascade="all, delete-orphan",
    )
    """Tool calls made during this task's execution."""
    
    __table_args__ = (
        CheckConstraint(
            "status IN ('pending', 'running', 'completed', 'failed', 'cancelled')",
            name="ck_tasks_status",
        ),
        CheckConstraint(
            "priority IN ('low', 'normal', 'high', 'critical')",
            name="ck_tasks_priority",
        ),
        CheckConstraint(
            "retry_count >= 0",
            name="ck_tasks_retry_count",
        ),
        CheckConstraint(
            "max_retries >= 0",
            name="ck_tasks_max_retries",
        ),
        Index("idx_tasks_status", "status", "created_at"),
        Index("idx_tasks_user", "user_id", "created_at"),
        Index("idx_tasks_agent", "agent_id", "created_at"),
        Index(
            "idx_tasks_scheduled",
            "scheduled_at",
            postgresql_where=(status == 'pending'),
        ),
    )
    
    def __repr__(self) -> str:
        return f"<Task(id={self.id}, user_id={self.user_id}, task_type={self.task_type!r}, status={self.status!r})>"
