# pyright: reportMissingImports=false
"""
SQLAlchemy model for task queue.

This module defines the database schema for task queue management,
including queue entries, claiming, retries, and execution tracking.
"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import TYPE_CHECKING, Any, Optional
from uuid import UUID

from sqlalchemy import (
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID as PostgreSQLUUID
from sqlalchemy.orm import Mapped, relationship, mapped_column

from db.base import Base
from db.types import TaskStatus

if TYPE_CHECKING:
    from db.schema.tasks import Task
    from db.schema.agents import AgentInstance
    from db.schema.dead_letter_queue import DeadLetterQueue


def gen_random_uuid() -> UUID:
    """Generate a random UUID v4 for database default."""
    import uuid
    return uuid.uuid4()


def now_utc() -> datetime:
    """Get current UTC datetime."""
    return datetime.now(timezone.utc)


class TaskQueue(Base):
    """Task queue model for managing task execution order and status.
    
    This table stores queue entries for tasks, tracking their execution
    priority, scheduling, claiming by agents, retry attempts, and results.
    
    The queue supports:
    - Priority-based ordering (higher priority = executed first)
    - Scheduled execution (scheduled_at for delayed tasks)
    - Agent claiming (claimed_by for distributed processing)
    - Retry logic (retry_count against max_retries)
    - Error tracking and result storage
    
    Key indexes:
    - idx_queue_poll: Efficient polling for pending tasks (priority DESC, scheduled_at ASC)
    - idx_queue_claimed: Active task tracking by agent (claimed_by WHERE status = 'running')
    - idx_queue_retry: Retry monitoring (retry_count WHERE status = 'pending')
    """
    
    __tablename__ = "task_queue"
    
    id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        primary_key=True,
        default=gen_random_uuid,
        server_default=func.gen_random_uuid(),
    )
    """Primary key - UUID v4 generated by PostgreSQL."""
    
    task_id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        ForeignKey("tasks.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    """Foreign key reference to the task (CASCADE delete)."""
    
    status: Mapped[TaskStatus] = mapped_column(
        String(50),
        nullable=False,
        default=TaskStatus.pending,
        server_default=TaskStatus.pending.value,
    )
    """Current queue status: pending, running, completed, failed, cancelled."""
    
    priority: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
        server_default="0",
    )
    """Task priority (higher number = higher priority, processed first)."""
    
    queued_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=now_utc,
        server_default=func.now(),
    )
    """Timestamp when task was added to the queue."""
    
    scheduled_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )
    """When task should become available for processing (NULL = immediate)."""
    
    started_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )
    """Task execution start timestamp."""
    
    completed_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )
    """Task completion timestamp (success or failure)."""
    
    claimed_by: Mapped[Optional[UUID]] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        ForeignKey("agent_instances.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    """Foreign key reference to the claiming agent instance (SET NULL on delete)."""
    
    claimed_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )
    """Timestamp when task was claimed by an agent."""
    
    retry_count: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
        server_default="0",
    )
    """Number of retry attempts made for this task."""
    
    max_retries: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=3,
        server_default="3",
    )
    """Maximum number of retry attempts allowed."""
    
    error_message: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
    )
    """Error message if task execution failed."""
    
    result_json: Mapped[Optional[dict[str, Any]]] = mapped_column(
        JSONB,
        nullable=True,
    )
    """JSONB field for task execution results."""
    
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=now_utc,
        server_default=func.now(),
    )
    """Record creation timestamp (UTC)."""
    
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=now_utc,
        server_default=func.now(),
        onupdate=now_utc,
    )
    """Last update timestamp (UTC)."""
    
    # Relationships
    task: Mapped["Task"] = relationship(
        back_populates="queue_entries",
    )
    """The task this queue entry belongs to."""
    
    claiming_agent: Mapped[Optional["AgentInstance"]] = relationship(
        back_populates="claimed_tasks",
    )
    """The agent instance that claimed this task."""
    
    dlq_entries: Mapped[list["DeadLetterQueue"]] = relationship(
        back_populates="original_queue_entry",
    )
    """Dead letter queue entries for this queue entry (if any)."""
    
    __table_args__ = (
        CheckConstraint(
            "status IN ('pending', 'running', 'completed', 'failed', 'cancelled')",
            name="ck_task_queue_status",
        ),
        CheckConstraint(
            "retry_count >= 0",
            name="ck_task_queue_retry_count",
        ),
        CheckConstraint(
            "max_retries >= 0",
            name="ck_task_queue_max_retries",
        ),
        CheckConstraint(
            "priority >= 0",
            name="ck_task_queue_priority",
        ),
        # Partial index for queue polling: highest priority, earliest scheduled first
        # Only indexes pending tasks for efficient polling
        Index(
            "idx_queue_poll",
            priority.desc(),
            scheduled_at.asc(),
            postgresql_where=(status == 'pending'),
        ),
        # Partial index for active task tracking by agent
        # Only indexes running tasks for active task reporting
        Index(
            "idx_queue_claimed",
            "claimed_by",
            postgresql_where=(status == 'running'),
        ),
        # Partial index for retry monitoring
        # Only indexes pending tasks for retry monitoring
        Index(
            "idx_queue_retry",
            "retry_count",
            postgresql_where=(status == 'pending'),
        ),
    )
    
    def __repr__(self) -> str:
        return f"<TaskQueue(id={self.id}, task_id={self.task_id}, status={self.status!r}, priority={self.priority})>"