# pyright: reportMissingImports=false
"""
SQLAlchemy model for task dependencies.

This module defines the database schema for task dependencies using the
adjacency list pattern for efficient DAG (Directed Acyclic Graph) operations.
Task dependencies define relationships between tasks with types:
- sequential: Tasks must execute one after another in order
- parallel: Tasks can execute concurrently without dependencies
- conditional: Task execution depends on the outcome of another task
"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import TYPE_CHECKING, Any, Optional
from uuid import UUID

from sqlalchemy import (
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID as PostgreSQLUUID
from sqlalchemy.orm import Mapped, mapped_column

from db.base import Base
from db.types import DependencyType

if TYPE_CHECKING:
    from db.schema.tasks import Task


def gen_random_uuid() -> UUID:
    """Generate a random UUID v4 for database default."""
    import uuid
    return uuid.uuid4()


def now_utc() -> datetime:
    """Get current UTC datetime."""
    return datetime.now(timezone.utc)


class TaskDependency(Base):
    """Task dependency model for defining relationships between tasks.
    
    This table stores dependencies between tasks using the adjacency list pattern.
    Each record defines a relationship where:
    - parent_task_id: The task that must complete first (or condition source)
    - child_task_id: The task that depends on the parent
    - dependency_type: How the tasks relate (sequential, parallel, conditional)
    - condition_json: Optional condition logic for conditional dependencies
    
    The model enforces:
    - No self-references (a task cannot depend on itself)
    - No duplicate dependencies between the same task pair
    - CASCADE delete when either parent or child task is deleted
    """
    
    __tablename__ = "task_dependencies"
    
    id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        primary_key=True,
        default=gen_random_uuid,
        server_default=func.gen_random_uuid(),
    )
    """Primary key - UUID v4 generated by PostgreSQL."""
    
    parent_task_id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        ForeignKey("tasks.id", ondelete="CASCADE"),
        nullable=False,
        index=False,  # We'll create custom indexes below
    )
    """Foreign key to the parent task (CASCADE delete)."""
    
    child_task_id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        ForeignKey("tasks.id", ondelete="CASCADE"),
        nullable=False,
        index=False,  # We'll create custom indexes below
    )
    """Foreign key to the child task (CASCADE delete)."""
    
    dependency_type: Mapped[DependencyType] = mapped_column(
        String(50),
        nullable=False,
        default=DependencyType.sequential,
        server_default=DependencyType.sequential.value,
    )
    """Type of dependency: sequential, parallel, or conditional."""
    
    condition_json: Mapped[Optional[dict[str, Any]]] = mapped_column(
        JSONB,
        nullable=True,
    )
    """JSONB field for conditional dependency logic (if/when clauses)."""
    
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=now_utc,
        server_default=func.now(),
    )
    """Record creation timestamp (UTC)."""
    
    __table_args__ = (
        # Prevent self-referencing (task cannot depend on itself)
        CheckConstraint(
            "parent_task_id != child_task_id",
            name="ck_task_dependencies_no_self_reference",
        ),
        # Prevent duplicate dependencies between the same task pair
        UniqueConstraint(
            "parent_task_id",
            "child_task_id",
            name="uq_task_dependencies_parent_child",
        ),
        # Index for finding all dependencies of a task (as parent)
        Index("idx_deps_parent", "parent_task_id"),
        # Index for finding all tasks that depend on a task (as child)
        Index("idx_deps_child", "child_task_id"),
    )
    
    def __repr__(self) -> str:
        return (
            f"<TaskDependency(id={self.id}, "
            f"parent_task_id={self.parent_task_id}, "
            f"child_task_id={self.child_task_id}, "
            f"dependency_type={self.dependency_type!r})>"
        )