# pyright: reportMissingImports=false, reportUndefinedVariable=false
"""
SQLAlchemy models for token usage tracking.

This module defines the database schema for tracking LLM token consumption
and estimated costs per user and agent session.
"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import TYPE_CHECKING, Optional
from uuid import UUID

from sqlalchemy import (
    Column,
    DateTime,
    ForeignKey,
    Index,
    Numeric,
    String,
    Text,
    func,
)
from sqlalchemy.dialects.postgresql import UUID as PostgreSQLUUID
from sqlalchemy.orm import Mapped, relationship, mapped_column

from db.base import Base

if TYPE_CHECKING:
    from db.schema.users import User
    from db.schema.agents import AgentInstance


def gen_random_uuid() -> UUID:
    """Generate a random UUID v4 for database default."""
    import uuid
    return uuid.uuid4()


def now_utc() -> datetime:
    """Get current UTC datetime."""
    return datetime.now(timezone.utc)


class TokenUsage(Base):
    """Token usage tracking model.
    
    This table tracks LLM token consumption and estimated costs
    for each user session and agent interaction.
    Foreign keys to users and agent_instances with CASCADE delete.
    """
    
    __tablename__ = "token_usage"
    
    id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        primary_key=True,
        default=gen_random_uuid,
        server_default=func.gen_random_uuid(),
    )
    """Primary key - UUID v4 generated by PostgreSQL."""
    
    user_id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=False,  # Custom index defined in __table_args__
    )
    """Foreign key reference to the user who made the request."""
    
    agent_id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        ForeignKey("agent_instances.id", ondelete="CASCADE"),
        nullable=False,
        index=False,  # Custom index defined in __table_args__
    )
    """Foreign key reference to the agent instance that processed the request."""
    
    session_id: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        index=False,  # Custom index defined in __table_args__
    )
    """Session identifier for grouping related requests."""
    
    model_name: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )
    """Name of the LLM model used (e.g., 'gpt-4', 'claude-3')."""
    
    input_tokens: Mapped[int] = mapped_column(
        nullable=False,
    )
    """Number of tokens in the input/prompt."""
    
    output_tokens: Mapped[int] = mapped_column(
        nullable=False,
    )
    """Number of tokens in the output/completion."""
    
    total_tokens: Mapped[int] = mapped_column(
        nullable=False,
    )
    """Total tokens used (input + output)."""
    
    estimated_cost_usd: Mapped[float] = mapped_column(
        Numeric(10, 6),
        nullable=False,
    )
    """Estimated cost in USD (6 decimal places for precision)."""
    
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=now_utc,
        server_default=func.now(),
    )
    """Record creation timestamp (UTC)."""
    
    # Relationships
    user: Mapped["User"] = relationship(
        "User",
        back_populates="token_usages",
    )
    """The user who made this request."""
    
    agent: Mapped["AgentInstance"] = relationship(
        "AgentInstance",
        back_populates="token_usages",
    )
    """The agent instance that processed this request."""
    
    __table_args__ = (
        Index("idx_token_usage_user_created", "user_id", "created_at"),
        Index("idx_token_usage_session", "session_id"),
    )
    
    def __repr__(self) -> str:
        return f"<TokenUsage(id={self.id}, user_id={self.user_id}, agent_id={self.agent_id}, total_tokens={self.total_tokens}, cost={self.estimated_cost_usd})>"
