# pyright: reportMissingImports=false, reportUndefinedVariable=false
"""
SQLAlchemy models for tools and tool versions.

This module defines the database schema for tool registry and version management.
Tools are registered with their input/output schemas and configuration.
Each tool can have multiple versions, with one marked as default.
"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import TYPE_CHECKING, Optional
from uuid import UUID

from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    ForeignKey,
    String,
    Text,
    UniqueConstraint,
    CheckConstraint,
    Index,
    func,
)
from sqlalchemy.dialects.postgresql import UUID as PostgreSQLUUID
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, relationship, mapped_column

from db.base import Base

if TYPE_CHECKING:
    from db.schema.tool_calls import ToolCall


def now_utc() -> datetime:
    """Get current UTC datetime."""
    return datetime.now(timezone.utc)


class Tool(Base):
    """Tool model for tool registry.

    This table stores tool definitions with metadata.
    Each tool can have multiple versions in tool_versions table.
    """

    __tablename__ = "tools"

    id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        primary_key=True,
        default=lambda: __import__("uuid").uuid4(),
        server_default=func.gen_random_uuid(),
    )
    """Primary key - UUID v4 generated by PostgreSQL."""

    name: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        index=True,
    )
    """Unique tool name for identification."""

    description: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
    )
    """Human-readable description of the tool."""

    is_active: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=True,
        server_default="true",
    )
    """Whether the tool is currently active/available."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=now_utc,
        server_default=func.now(),
    )
    """Record creation timestamp (UTC)."""

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=now_utc,
        server_default=func.now(),
        onupdate=now_utc,
    )
    """Last update timestamp (UTC)."""

    # Relationship to tool versions
    versions: Mapped[list["ToolVersion"]] = relationship(  # type: ignore[name-defined]
        "ToolVersion",
        back_populates="tool",
        cascade="all, delete-orphan",
    )
    """Tool versions associated with this tool."""
    
    tool_calls: Mapped[list["ToolCall"]] = relationship(
        back_populates="tool",
        cascade="all, delete-orphan",
    )
    """Tool calls made using this tool."""

    __table_args__ = (
        UniqueConstraint("name", name="uq_tools_name"),
        Index("idx_tools_name", "name"),
        Index("idx_tools_is_active", "is_active"),
    )

    def __repr__(self) -> str:
        return f"<Tool(id={self.id}, name={self.name!r}, is_active={self.is_active})>"


class ToolVersion(Base):
    """Tool version model for versioned tool definitions.

    This table stores versioned tool definitions with schemas and configuration.
    Each tool can have multiple versions, with at most one marked as default.
    Foreign key to tools with cascade delete to prevent orphaned versions.
    """

    __tablename__ = "tool_versions"

    id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        primary_key=True,
        default=lambda: __import__("uuid").uuid4(),
        server_default=func.gen_random_uuid(),
    )
    """Primary key - UUID v4 generated by PostgreSQL."""

    tool_id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        ForeignKey("tools.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    """Foreign key reference to the parent tool."""

    version: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
    )
    """Version string (e.g., '1.0.0', '2.1.3')."""

    input_schema: Mapped[Optional[dict]] = mapped_column(
        JSONB,
        nullable=True,
    )
    """JSON Schema for validating tool inputs."""

    output_schema: Mapped[Optional[dict]] = mapped_column(
        JSONB,
        nullable=True,
    )
    """JSON Schema for validating tool outputs."""

    implementation_ref: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
    )
    """Reference to implementation (e.g., module.path:function_name)."""

    config_json: Mapped[Optional[dict]] = mapped_column(
        JSONB,
        nullable=True,
    )
    """Tool-specific configuration as JSON."""

    is_default: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=False,
        server_default="false",
    )
    """Whether this is the default version for the tool."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=now_utc,
        server_default=func.now(),
    )
    """Record creation timestamp (UTC)."""

    # Relationship to tool
    tool: Mapped["Tool"] = relationship(  # type: ignore[name-defined]
        "Tool",
        back_populates="versions",
    )
    """The tool this version belongs to."""
    
    tool_calls: Mapped[list["ToolCall"]] = relationship(
        back_populates="tool_version",
    )
    """Tool calls made using this specific version."""

    __table_args__ = (
        Index(
            "idx_tool_versions_default",
            "tool_id",
            postgresql_where=func.coalesce(is_default, False) == True,
            unique=True,
        ),
        Index("idx_tool_versions_tool_id", "tool_id"),
        Index("idx_tool_versions_version", "version"),
    )

    def __repr__(self) -> str:
        return f"<ToolVersion(id={self.id}, tool_id={self.tool_id}, version={self.version!r}, is_default={self.is_default})>"
