services:
  embedding-api:
    container_name: embedding-ai
    image: ghcr.io/huggingface/text-embeddings-inference:latest
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - NVIDIA_DISABLE_REQUIRE=true  # 關鍵：禁用要求檢查
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    ports:
      - "8605:80"
    volumes:
      - /mnt/models/huggingface/hub/:/data
    command: --model-id BAAI/bge-m3

  reranker-api:
    container_name: reranker-ai
    image: ghcr.io/huggingface/text-embeddings-inference:latest
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - NVIDIA_DISABLE_REQUIRE=true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    ports:
      - "8606:80"
    volumes:
      - /mnt/models/huggingface/hub/:/data
    command: --model-id BAAI/bge-reranker-v2-m3