# pyright: reportMissingImports=false, reportUndefinedVariable=false
"""
SQLAlchemy entity model for agent capabilities.

This module defines the database entity for agent capability definitions.
Mirrors the original schema from db/schema/agent_capabilities.py.
"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Optional
from uuid import UUID, uuid4

from sqlalchemy import (
    Boolean,
    DateTime,
    ForeignKey,
    Index,
    Text,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID as PostgreSQLUUID
from sqlalchemy.orm import Mapped, mapped_column

from db.entity.base import EntityBase as Base


def gen_random_uuid() -> UUID:
    """Generate a random UUID v4 for database default."""
    return uuid4()


def now_utc() -> datetime:
    """Get current UTC datetime."""
    return datetime.now(timezone.utc)


class AgentCapability(Base):
    """Agent capability definition entity.
    
    This table stores reusable capability definitions that can be
    associated with agent types. Each capability includes input/output
    schema definitions for validation.
    
    Table: agent_capabilities
    """
    
    __tablename__ = "agent_capabilities"
    
    id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        primary_key=True,
        default=gen_random_uuid,
        server_default=func.gen_random_uuid(),
    )
    """Primary key - UUID v4 generated by PostgreSQL."""
    
    agent_type_id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        ForeignKey("agent_types.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    """Foreign key reference to the agent type that owns this capability."""
    
    capability_name: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        index=True,
    )
    """Name of the capability."""
    
    description: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
    )
    """Human-readable description of the capability."""
    
    input_schema: Mapped[Optional[dict[str, Any]]] = mapped_column(
        JSONB,
        nullable=True,
    )
    """JSONB field storing JSON Schema definition for input validation."""
    
    output_schema: Mapped[Optional[dict[str, Any]]] = mapped_column(
        JSONB,
        nullable=True,
    )
    """JSONB field storing JSON Schema definition for output validation."""
    
    is_active: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=True,
        server_default="true",
    )
    """Whether the capability is currently active and available."""
    
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=now_utc,
        server_default=func.now(),
    )
    """Record creation timestamp (UTC)."""
    
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=now_utc,
        server_default=func.now(),
        onupdate=now_utc,
    )
    """Last update timestamp (UTC)."""
    
    __table_args__ = (
        Index("idx_capabilities_type", "agent_type_id"),
        Index("idx_capabilities_name", "capability_name"),
        {"extend_existing": True},
    )
    
    def __repr__(self) -> str:
        return f"<AgentCapability(id={self.id}, agent_type_id={self.agent_type_id}, capability_name={self.capability_name!r}, is_active={self.is_active})>"