# pyright: reportMissingImports=false, reportUndefinedVariable=false
"""
SQLAlchemy entity models for agent types and agent instances.

This module defines the database entities for agent management.
Mirrors the original schema from db/schema/agents.py.
"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import TYPE_CHECKING, Any, Optional
from uuid import UUID, uuid4

from sqlalchemy import (
    Boolean,
    DateTime,
    ForeignKey,
    Index,
    Text,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID as PostgreSQLUUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from db.entity.base import EntityBase as Base


def gen_random_uuid() -> UUID:
    """Generate a random UUID v4 for database default."""
    return uuid4()


def now_utc() -> datetime:
    """Get current UTC datetime."""
    return datetime.now(timezone.utc)


class AgentType(Base):
    """Agent type entity for categorizing agents.
    
    Table: agent_types
    """
    
    __tablename__ = "agent_types"
    
    id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        primary_key=True,
        default=gen_random_uuid,
        server_default=func.gen_random_uuid(),
    )
    """Primary key - UUID v4 generated by PostgreSQL."""
    
    name: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        unique=True,
        index=True,
    )
    """Unique name for the agent type."""
    
    description: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
    )
    """Human-readable description of the agent type."""
    
    capabilities: Mapped[Optional[dict[str, Any]]] = mapped_column(
        JSONB,
        nullable=True,
    )
    """JSONB field storing agent capabilities as key-value pairs."""
    
    default_config: Mapped[Optional[dict[str, Any]]] = mapped_column(
        JSONB,
        nullable=True,
    )
    """JSONB field storing default configuration for this agent type."""
    
    is_active: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=True,
        server_default="true",
    )
    """Whether the agent type is currently active and available."""
    
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=now_utc,
        server_default=func.now(),
    )
    """Record creation timestamp (UTC)."""
    
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=now_utc,
        server_default=func.now(),
        onupdate=now_utc,
    )
    """Last update timestamp (UTC)."""
    
    __table_args__ = (
        Index("idx_agent_types_is_active", "is_active"),
        {"extend_existing": True},
    )


class AgentInstance(Base):
    """Agent instance entity.
    
    Table: agent_instances
    """
    
    __tablename__ = "agent_instances"
    
    id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        primary_key=True,
        default=gen_random_uuid,
        server_default=func.gen_random_uuid(),
    )
    """Primary key - UUID v4 generated by PostgreSQL."""
    
    agent_type_id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        ForeignKey("agent_types.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    """Foreign key reference to the agent type."""
    
    user_id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=False,
    )
    """Foreign key reference to the owning user."""
    
    name: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
    )
    """Optional human-readable name for this instance."""
    
    status: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        default="idle",
        server_default="idle",
    )
    """Current operational status of the agent instance."""
    
    config: Mapped[Optional[dict[str, Any]]] = mapped_column(
        JSONB,
        nullable=True,
    )
    """JSONB field storing instance-specific configuration overrides."""
    
    last_heartbeat_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )
    """Last heartbeat timestamp for liveness detection."""

    agent_id: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
        unique=True,
        index=True,
        comment="Unique identifier for agent instance",
    )
    """Unique string identifier for this agent instance (e.g. 'butler-001')."""

    endpoint_group_id: Mapped[Optional[UUID]] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        ForeignKey("llm_endpoint_groups.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
        comment="Reference to LLM endpoint group configuration",
    )
    """Foreign key to the LLM endpoint group assigned to this instance."""

    phone_no: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
        comment="Agent phone number in free-form format",
    )
    """Phone number associated with this agent instance."""

    whatsapp_key: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
        comment="WhatsApp authentication key for agent",
    )
    """WhatsApp authentication key for this agent instance."""

    # Relationship to llm_endpoint_group
    endpoint_group: Mapped[Optional["LLMEndpointGroup"]] = relationship(  # type: ignore[name-defined]
        "LLMEndpointGroup",
        foreign_keys=[endpoint_group_id],
        lazy="select",
    )
    """The LLM endpoint group assigned to this agent instance."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=now_utc,
        server_default=func.now(),
    )
    """Record creation timestamp (UTC)."""
    
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=now_utc,
        server_default=func.now(),
        onupdate=now_utc,
    )
    """Last update timestamp (UTC)."""
    
    __table_args__ = (
        Index("idx_agent_instances_status", "status"),
        Index("idx_agent_instances_user", "user_id"),
        Index("idx_agent_instances_endpoint_group_id", "endpoint_group_id"),
        {"extend_existing": True},
    )


# Type checking imports for forward references
if TYPE_CHECKING:
    from db.entity.llm_endpoint_entity import LLMEndpointGroup