# pyright: reportMissingImports=false, reportUndefinedVariable=false
"""
SQLAlchemy entity model for audit logging.

This module defines the database entity for audit logging,
capturing all actions performed on resources in the system.
Mirrors the original schema from db/schema/audit.py.
"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import TYPE_CHECKING, Optional
from uuid import UUID, uuid4

from sqlalchemy import (
    DateTime,
    Enum,
    Text,
    func,
)
from sqlalchemy.dialects.postgresql import INET, JSONB, UUID as PostgreSQLUUID
from sqlalchemy.orm import Mapped, mapped_column

from db.entity.base import EntityBase as Base
from db.types import ActorType


def gen_random_uuid() -> UUID:
    """Generate a random UUID v4 for database default."""
    return uuid4()


def now_utc() -> datetime:
    """Get current UTC datetime."""
    return datetime.now(timezone.utc)


class AuditLog(Base):
    """Audit log entity for tracking system actions.
    
    This table stores immutable audit records of all actions
    performed on resources in the system. Each record captures
    who performed the action, what action was taken, and the
    before/after state of the resource.
    
    The audit log is append-only - records should never be
    updated or deleted once created.
    
    Table: audit.audit_log
    Schema: audit
    """
    
    __tablename__ = "audit_log"
    __table_args__ = (
        {"schema": "audit", "extend_existing": True},
    )
    
    id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        primary_key=True,
        default=gen_random_uuid,
        server_default=func.gen_random_uuid(),
    )
    """Primary key - UUID v4 generated by PostgreSQL."""
    
    user_id: Mapped[Optional[UUID]] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        nullable=True,
    )
    """Optional reference to the user who performed the action.
    
    Can be null for system or agent actions without an associated user.
    """
    
    actor_type: Mapped[ActorType] = mapped_column(
        Enum(
            ActorType,
            name="actor_type_enum",
            schema="audit",
        ),
        nullable=False,
    )
    """Type of actor performing the action (user/agent/system)."""
    
    actor_id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        nullable=False,
    )
    """ID of the actor that performed the action.
    
    For user actions, this matches user_id.
    For agent actions, this is the agent ID.
    For system actions, this is a system identifier.
    """
    
    action: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )
    """The action performed (e.g., create/update/delete/execute)."""
    
    resource_type: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )
    """Type of resource affected (e.g., user, task, agent)."""
    
    resource_id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        nullable=False,
    )
    """ID of the resource affected by the action."""
    
    old_values: Mapped[Optional[dict]] = mapped_column(
        JSONB,
        nullable=True,
    )
    """Previous state of the resource (before the action).
    
    For create actions, this is null.
    For update actions, contains changed fields.
    For delete actions, contains the full deleted record.
    """
    
    new_values: Mapped[Optional[dict]] = mapped_column(
        JSONB,
        nullable=True,
    )
    """New state of the resource (after the action).
    
    For create actions, contains the full created record.
    For update actions, contains changed fields.
    For delete actions, this is null.
    """
    
    ip_address: Mapped[Optional[str]] = mapped_column(
        INET,
        nullable=True,
    )
    """IP address from which the action originated."""
    
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=now_utc,
        server_default=func.now(),
        index=True,
    )
    """Record creation timestamp (UTC)."""
    
    def __repr__(self) -> str:
        return (
            f"<AuditLog(id={self.id}, actor_type={self.actor_type!r}, "
            f"action={self.action!r}, resource_type={self.resource_type!r})>"
        )


# Type checking imports for forward references
if TYPE_CHECKING:
    pass  # Additional entity imports will be added as needed