# pyright: reportMissingImports=false
"""
SQLAlchemy entity models for collaboration sessions and agent messages.

This module defines the database entities for multi-agent collaboration,
including session management and inter-agent message tracking.
Mirrors the original schema from db/schema/collaboration.py.

Import path: db.entity.collaboration_entity
"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import TYPE_CHECKING, Any, Optional
from uuid import UUID, uuid4

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID as PostgreSQLUUID
from sqlalchemy.orm import Mapped, mapped_column

from db.entity.base import EntityBase as Base
from db.types import CollaborationStatus, MessageRedactionLevel, MessageType


def gen_random_uuid() -> UUID:
    """Generate a random UUID v4 for database default."""
    return uuid4()


def now_utc() -> datetime:
    """Get current UTC datetime."""
    return datetime.now(timezone.utc)


class CollaborationSession(Base):
    """Collaboration session entity.
    
    This table stores multi-agent collaboration sessions, tracking
    which agents are collaborating and the shared context.
    
    Table: collaboration_sessions
    """
    
    __tablename__ = "collaboration_sessions"
    
    id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        primary_key=True,
        default=gen_random_uuid,
        server_default=func.gen_random_uuid(),
    )
    """Primary key - UUID v4 generated by PostgreSQL."""
    
    user_id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    """Foreign key reference to the owning user."""
    
    main_agent_id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        ForeignKey("agent_instances.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    """Foreign key reference to the main coordinating agent instance."""
    
    name: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
    )
    """Optional human-readable name for the collaboration session."""
    
    session_id: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        unique=True,
    )
    """Unique session identifier with prefixes (session-{uuid}, default-{uuid}, ghost-{uuid}, refl-{uuid})."""
    
    status: Mapped[CollaborationStatus] = mapped_column(
        String(50),
        nullable=False,
        default=CollaborationStatus.active,
        server_default=CollaborationStatus.active.value,
    )
    """Current status of the collaboration session."""
    
    involves_secrets: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=False,
        server_default="false",
    )
    """Whether this collaboration involves sensitive/secrets data."""
    
    context_json: Mapped[Optional[dict[str, Any]]] = mapped_column(
        JSONB,
        nullable=True,
    )
    """JSONB field storing shared session context as key-value pairs."""
    
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=now_utc,
        server_default=func.now(),
    )
    """Record creation timestamp (UTC)."""
    
    ended_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )
    """Session end timestamp (UTC)."""
    
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=now_utc,
        server_default=func.now(),
        onupdate=now_utc,
    )
    """Last update timestamp (UTC)."""
    
    __table_args__ = (
        CheckConstraint(
            "status IN ('active', 'completed', 'failed', 'cancelled')",
            name="ck_collaboration_sessions_status",
        ),
        UniqueConstraint("session_id", name="uq_collaboration_sessions_session_id"),
        Index("idx_collab_user", "user_id"),
        Index("idx_collab_status", "status"),
        {"extend_existing": True},
    )
    
    def __repr__(self) -> str:
        return f"<CollaborationSession(id={self.id}, user_id={self.user_id}, status={self.status!r})>"


class AgentMessage(Base):
    """Agent message entity.
    
    This table stores messages exchanged between agents during
    collaboration sessions, with step tracking for conversation flows.
    
    Table: agent_messages
    """
    
    __tablename__ = "agent_messages"
    
    id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        primary_key=True,
        default=gen_random_uuid,
        server_default=func.gen_random_uuid(),
    )
    """Primary key - UUID v4 generated by PostgreSQL."""
    
    collaboration_id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        ForeignKey("collaboration_sessions.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    """Foreign key reference to the collaboration session."""
    
    step_id: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
    )
    """Optional step identifier grouping related messages in an interaction flow."""
    
    sender_agent_id: Mapped[Optional[UUID]] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        ForeignKey("agent_instances.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    """Foreign key reference to the sending agent instance."""
    
    receiver_agent_id: Mapped[Optional[UUID]] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        ForeignKey("agent_instances.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    """Foreign key reference to the receiving agent instance."""
    
    message_type: Mapped[MessageType] = mapped_column(
        String(50),
        nullable=False,
        default=MessageType.request,
        server_default=MessageType.request.value,
    )
    """Type of the message (request/response/notification/ack/tool_call/tool_result)."""
    
    content_json: Mapped[dict[str, Any]] = mapped_column(
        JSONB,
        nullable=False,
    )
    """JSONB field storing structured message content."""
    
    redaction_level: Mapped[MessageRedactionLevel] = mapped_column(
        String(50),
        nullable=False,
        default=MessageRedactionLevel.none,
        server_default=MessageRedactionLevel.none.value,
    )
    """Redaction level for message content."""
    
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=now_utc,
        server_default=func.now(),
    )
    """Message creation timestamp (UTC)."""
    
    __table_args__ = (
        CheckConstraint(
            "message_type IN ('request', 'response', 'notification', 'ack', 'tool_call', 'tool_result')",
            name="ck_agent_messages_message_type",
        ),
        CheckConstraint(
            "redaction_level IN ('none', 'partial', 'full')",
            name="ck_agent_messages_redaction_level",
        ),
        Index("idx_messages_collab", "collaboration_id", "created_at"),
        Index("idx_messages_step", "step_id"),
        {"extend_existing": True},
    )
    
    def __repr__(self) -> str:
        return f"<AgentMessage(id={self.id}, collaboration_id={self.collaboration_id}, type={self.message_type!r})>"


# Type checking imports for forward references
if TYPE_CHECKING:
    pass  # No forward references needed currently