# pyright: reportMissingImports=false, reportUndefinedVariable=false
"""
SQLAlchemy entity models for LLM endpoint groups, endpoints, and level endpoints.

This module defines the database entities for LLM endpoint management,
including groups for organization, individual endpoints with encrypted API keys,
and level-based endpoint assignments.

Mirrors the original schema from db/schema/llm_endpoints.py.
"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import TYPE_CHECKING, Any, Optional
from uuid import UUID, uuid4

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    SmallInteger,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID as PostgreSQLUUID
from sqlalchemy.orm import Mapped, relationship, mapped_column

from db.entity.base import EntityBase as Base


def gen_random_uuid() -> UUID:
    """Generate a random UUID v4 for database default."""
    return uuid4()


def now_utc() -> datetime:
    """Get current UTC datetime."""
    return datetime.now(timezone.utc)


class LLMEndpointGroup(Base):
    """LLM endpoint group entity for organizing LLM API endpoints.
    
    This table stores user-defined groups for organizing LLM endpoints.
    Each user can have multiple endpoint groups, but only one can be
    marked as the default group per user.
    
    Table: llm_endpoint_groups
    """
    
    __tablename__ = "llm_endpoint_groups"
    
    id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        primary_key=True,
        default=gen_random_uuid,
        server_default=func.gen_random_uuid(),
    )
    """Primary key - UUID v4 generated by PostgreSQL."""
    
    user_id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=False,  # We'll create a custom index below
    )
    """Foreign key reference to the owning user."""
    
    name: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )
    """Name of the endpoint group."""
    
    description: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
    )
    """Optional description of the endpoint group."""
    
    is_default: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=False,
        server_default="false",
    )
    """Whether this is the user's default endpoint group (only one per user)."""
    
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=now_utc,
        server_default=func.now(),
    )
    """Record creation timestamp (UTC)."""
    
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=now_utc,
        server_default=func.now(),
        onupdate=now_utc,
    )
    """Last update timestamp (UTC)."""
    
    # Relationship to user
    user: Mapped["User"] = relationship(  # type: ignore[name-defined]
        "User",
        back_populates="llm_endpoint_groups",
    )
    """The user who owns this endpoint group."""
    
    # Relationship to level endpoints
    level_endpoints: Mapped[list["LLMLevelEndpoint"]] = relationship(
        "LLMLevelEndpoint",
        back_populates="group",
        cascade="all, delete-orphan",
    )
    """Level endpoint assignments for this group."""
    
    __table_args__ = (
        UniqueConstraint("name", "user_id", name="uq_llm_endpoint_groups_name_per_user"),
        Index("idx_llm_endpoint_groups_user", "user_id"),
        Index(
            "idx_llm_endpoint_groups_default",
            "user_id",
            unique=True,
            postgresql_where=func.coalesce(is_default, False) == True,
        ),
        {"extend_existing": True},
    )
    
    def __repr__(self) -> str:
        return f"<LLMEndpointGroup(id={self.id}, user_id={self.user_id}, name={self.name!r}, is_default={self.is_default})>"


class LLMEndpoint(Base):
    """LLM endpoint entity for storing API endpoint configurations.
    
    This table stores individual LLM API endpoint configurations with
    encrypted API keys. Each endpoint belongs to a user and can be
    assigned to multiple groups via LLMLevelEndpoint.
    
    IMPORTANT: API keys are stored encrypted using Fernet (AES-128) encryption.
    Never store or log API keys in plaintext.
    
    Table: llm_endpoints
    """
    
    __tablename__ = "llm_endpoints"
    
    id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        primary_key=True,
        default=gen_random_uuid,
        server_default=func.gen_random_uuid(),
    )
    """Primary key - UUID v4 generated by PostgreSQL."""
    
    user_id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=False,  # We'll create a custom index below
    )
    """Foreign key reference to the owning user."""
    
    name: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )
    """Human-readable name for this endpoint configuration."""
    
    base_url: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )
    """Base URL for the LLM API endpoint (e.g., 'https://api.openai.com/v1')."""
    
    api_key_encrypted: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )
    """Encrypted API key for authentication. Stored using Fernet encryption, never plaintext."""
    
    model_name: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )
    """Name of the model to use (e.g., 'gpt-4', 'claude-3-opus')."""
    
    config_json: Mapped[Optional[dict[str, Any]]] = mapped_column(
        JSONB,
        nullable=True,
    )
    """JSONB field for advanced configuration settings (temperature, max_tokens, etc.)."""
    
    is_active: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=True,
        server_default="true",
    )
    """Whether this endpoint is currently active and available for use."""
    
    last_success_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )
    """Timestamp of the last successful API call to this endpoint."""
    
    last_failure_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )
    """Timestamp of the last failed API call to this endpoint."""
    
    failure_count: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
        server_default="0",
    )
    """Count of consecutive failures. Reset on successful call."""
    
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=now_utc,
        server_default=func.now(),
    )
    """Record creation timestamp (UTC)."""
    
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=now_utc,
        server_default=func.now(),
        onupdate=now_utc,
    )
    """Last update timestamp (UTC)."""
    
    # Relationship to user
    user: Mapped["User"] = relationship(  # type: ignore[name-defined]
        "User",
        back_populates="llm_endpoints",
    )
    """The user who owns this endpoint."""
    
    # Relationship to level endpoints
    level_assignments: Mapped[list["LLMLevelEndpoint"]] = relationship(
        "LLMLevelEndpoint",
        back_populates="endpoint",
        cascade="all, delete-orphan",
    )
    """Level endpoint assignments that reference this endpoint."""
    
    __table_args__ = (
        Index("idx_endpoints_user", "user_id"),
        {"extend_existing": True},
    )
    
    def __repr__(self) -> str:
        return f"<LLMEndpoint(id={self.id}, user_id={self.user_id}, name={self.name!r}, model_name={self.model_name!r})>"


class LLMLevelEndpoint(Base):
    """Level-based endpoint assignment entity.
    
    This table maps endpoints to groups based on difficulty level and
    whether secrets are involved. This allows different endpoints to be
    used for different complexity tasks and security requirements.
    
    Difficulty levels:
    - 1: Simple tasks (quick, straightforward operations)
    - 2: Medium tasks (moderate complexity)
    - 3: Complex tasks (multi-step, reasoning-heavy operations)
    
    Table: llm_level_endpoints
    """
    
    __tablename__ = "llm_level_endpoints"
    
    id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        primary_key=True,
        default=gen_random_uuid,
        server_default=func.gen_random_uuid(),
    )
    """Primary key - UUID v4 generated by PostgreSQL."""
    
    group_id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        ForeignKey("llm_endpoint_groups.id", ondelete="CASCADE"),
        nullable=False,
        index=False,  # We'll create a custom index below
    )
    """Foreign key reference to the endpoint group."""
    
    difficulty_level: Mapped[int] = mapped_column(
        SmallInteger,
        nullable=False,
    )
    """Difficulty level: 1 (simple), 2 (medium), or 3 (complex)."""
    
    involves_secrets: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=False,
        server_default="false",
    )
    """Whether this endpoint assignment involves handling secrets/sensitive data."""
    
    endpoint_id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        ForeignKey("llm_endpoints.id", ondelete="CASCADE"),
        nullable=False,
        unique=True,
    )
    """Foreign key reference to the LLM endpoint (unique constraint)."""
    
    priority: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
        server_default="0",
    )
    """Priority for endpoint selection within the same level (higher = preferred)."""
    
    is_active: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=True,
        server_default="true",
    )
    """Whether this level endpoint assignment is active."""
    
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=now_utc,
        server_default=func.now(),
    )
    """Record creation timestamp (UTC)."""
    
    # Relationship to group
    group: Mapped["LLMEndpointGroup"] = relationship(
        "LLMEndpointGroup",
        back_populates="level_endpoints",
    )
    """The endpoint group this assignment belongs to."""
    
    # Relationship to endpoint
    endpoint: Mapped["LLMEndpoint"] = relationship(
        "LLMEndpoint",
        back_populates="level_assignments",
    )
    """The endpoint being assigned."""
    
    __table_args__ = (
        CheckConstraint(
            "difficulty_level BETWEEN 1 AND 3",
            name="ck_llm_level_endpoints_difficulty_level",
        ),
        UniqueConstraint(
            "group_id", "difficulty_level", "involves_secrets", "endpoint_id",
            name="uq_llm_level_endpoints_group_level_secrets_endpoint",
        ),
        Index("idx_level_endpoints_group", "group_id"),
        {"extend_existing": True},
    )
    
    def __repr__(self) -> str:
        return f"<LLMLevelEndpoint(id={self.id}, group_id={self.group_id}, difficulty_level={self.difficulty_level}, endpoint_id={self.endpoint_id})>"


# Type checking imports for forward references
if TYPE_CHECKING:
    from db.entity.user_entity import User