# pyright: reportMissingImports=false, reportUndefinedVariable=false
"""
SQLAlchemy entity model for MCP tools.

This module defines the database entity for MCP tools mapping.
Each MCP tool represents a tool provided by an MCP server and mapped to our tools table.

Import path: src.db.entity.mcp_tool_entity
"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import TYPE_CHECKING, Optional
from uuid import UUID, uuid4

from sqlalchemy import (
    Boolean,
    DateTime,
    ForeignKey,
    Integer,
    Text,
    UniqueConstraint,
    Index,
    func,
)
from sqlalchemy.dialects.postgresql import UUID as PostgreSQLUUID
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, relationship, mapped_column

from db.entity.base import EntityBase as Base

if TYPE_CHECKING:
    from db.entity.mcp_client_entity import MCPClient
    from db.entity.tool_entity import Tool


def gen_random_uuid() -> UUID:
    """Generate a random UUID v4 for database default."""
    return uuid4()


def now_utc() -> datetime:
    """Get current UTC datetime."""
    return datetime.now(timezone.utc)


class MCPTool(Base):
    """MCP Tool entity for MCP tool mappings.

    This table stores mappings between MCP server tools and our internal tools table.
    Each record represents a tool provided by an MCP server.

    Table: mcp_tools
    """

    __tablename__ = "mcp_tools"

    id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        primary_key=True,
        default=gen_random_uuid,
        server_default=func.gen_random_uuid(),
    )
    """Primary key - UUID v4 generated by PostgreSQL."""

    mcp_client_id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        ForeignKey("mcp_clients.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    """Foreign key reference to the MCP client providing this tool."""

    tool_id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        ForeignKey("tools.id"),
        nullable=False,
        index=True,
    )
    """Foreign key reference to the internal tool."""

    # MCP tool info
    mcp_tool_name: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        index=True,
    )
    """Original tool name from MCP server."""

    mcp_tool_description: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
    )
    """Tool description from MCP server."""

    mcp_tool_schema: Mapped[Optional[dict]] = mapped_column(
        JSONB,
        nullable=True,
    )
    """Tool input schema from MCP server (JSON Schema format)."""

    # Control/Tracking
    is_active: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=True,
        server_default="true",
    )
    """Whether this tool mapping is currently active."""

    last_invoked_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )
    """Last invocation timestamp (UTC)."""

    invocation_count: Mapped[int] = mapped_column(
        Integer,
        nullable=True,
        default=0,
        server_default="0",
    )
    """Total number of times this tool has been invoked."""

    # Metadata
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=now_utc,
        server_default=func.now(),
    )
    """Record creation timestamp (UTC)."""

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=now_utc,
        server_default=func.now(),
        onupdate=now_utc,
    )
    """Last update timestamp (UTC)."""

    # Relationships
    mcp_client: Mapped["MCPClient"] = relationship(
        "MCPClient",
        back_populates="tools",
    )
    """The MCP client providing this tool."""

    tool: Mapped["Tool"] = relationship(
        "Tool",
    )
    """The internal tool this MCP tool maps to."""

    __table_args__ = (
        UniqueConstraint('mcp_client_id', 'tool_id', name='uq_mcp_tools_client_tool'),
        Index("idx_mcp_tools_client", "mcp_client_id"),
        Index("idx_mcp_tools_tool", "tool_id"),
        Index("idx_mcp_tools_active", "is_active"),
        Index("idx_mcp_tools_name", "mcp_tool_name"),
        {"extend_existing": True},
    )

    def __repr__(self) -> str:
        return f"<MCPTool(id={self.id}, mcp_tool_name={self.mcp_tool_name!r}, is_active={self.is_active})>"
