# pyright: reportMissingImports=false, reportUndefinedVariable=false
"""
SQLAlchemy entity model for MCP clients.

This module defines the database entity for MCP (Model Context Protocol) client management.
Each MCP client represents a connection to an external MCP server.

Import path: src.db.entity.mcp_client_entity
"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import TYPE_CHECKING, Optional
from uuid import UUID, uuid4

from sqlalchemy import (
    Boolean,
    DateTime,
    ForeignKey,
    Integer,
    String,
    Text,
    CheckConstraint,
    Index,
    func,
)
from sqlalchemy.dialects.postgresql import UUID as PostgreSQLUUID
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, relationship, mapped_column

from db.entity.base import EntityBase as Base

if TYPE_CHECKING:
    from db.entity.mcp_tool_entity import MCPTool


def gen_random_uuid() -> UUID:
    """Generate a random UUID v4 for database default."""
    return uuid4()


def now_utc() -> datetime:
    """Get current UTC datetime."""
    return datetime.now(timezone.utc)


class MCPClient(Base):
    """MCP Client entity for MCP server connections.

    This table stores MCP client configurations and connection information.
    Each client represents a connection to an external MCP server.

    Table: mcp_clients
    """

    __tablename__ = "mcp_clients"

    id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        primary_key=True,
        default=gen_random_uuid,
        server_default=func.gen_random_uuid(),
    )
    """Primary key - UUID v4 generated by PostgreSQL."""

    user_id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    """Foreign key reference to the user who owns this client."""

    name: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )
    """Human-readable name for this MCP client."""

    description: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
    )
    """Optional description of the MCP client."""

    # Protocol/Config fields
    protocol: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )
    """Communication protocol: 'http' or 'websocket'."""

    base_url: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )
    """Base URL of the MCP server."""

    api_key_encrypted: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
    )
    """Encrypted API key for authentication (if required)."""

    headers: Mapped[Optional[dict]] = mapped_column(
        JSONB,
        nullable=True,
        server_default="{}",
    )
    """Custom HTTP headers as JSON."""

    # Auth config
    auth_type: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
    )
    """Authentication type: 'none', 'api_key', 'bearer', 'basic', 'oauth2'."""

    auth_config: Mapped[Optional[dict]] = mapped_column(
        JSONB,
        nullable=True,
        server_default="{}",
    )
    """Authentication configuration as JSON."""

    # Status/Connection
    status: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )
    """Connection status: 'connected', 'disconnected', 'error'."""

    last_connected_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )
    """Last successful connection timestamp (UTC)."""

    last_error: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
    )
    """Last error message (if any)."""

    # Metadata
    client_metadata: Mapped[Optional[dict]] = mapped_column(
        JSONB,
        nullable=True,
        server_default="{}",
    )
    """Additional metadata as JSON."""

    is_active: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=True,
        server_default="true",
    )
    """Whether the client is currently active."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=now_utc,
        server_default=func.now(),
    )
    """Record creation timestamp (UTC)."""

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=now_utc,
        server_default=func.now(),
        onupdate=now_utc,
    )
    """Last update timestamp (UTC)."""

    # Relationships
    tools: Mapped[list["MCPTool"]] = relationship(
        "MCPTool",
        back_populates="mcp_client",
        cascade="all, delete-orphan",
    )
    """MCP tools associated with this client."""

    __table_args__ = (
        CheckConstraint(
            "protocol IN ('http', 'websocket')",
            name='ck_mcp_clients_protocol'
        ),
        CheckConstraint(
            "auth_type IN ('none', 'api_key', 'bearer', 'basic', 'oauth2')",
            name='ck_mcp_clients_auth_type'
        ),
        CheckConstraint(
            "status IN ('connected', 'disconnected', 'error')",
            name='ck_mcp_clients_status'
        ),
        Index("idx_mcp_clients_user", "user_id"),
        Index("idx_mcp_clients_status", "status"),
        Index("idx_mcp_clients_active", "is_active"),
        {"extend_existing": True},
    )

    def __repr__(self) -> str:
        return f"<MCPClient(id={self.id}, name={self.name!r}, status={self.status})>"
