# pyright: reportMissingImports=false, reportUndefinedVariable=false
"""
SQLAlchemy entity model for task dependencies.

This module defines the database entity for task dependencies,
representing parent-child relationships between tasks.

Import path: src.db.entity.task_dependency_entity
"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import TYPE_CHECKING, Optional
from uuid import UUID, uuid4

from sqlalchemy import (
    CheckConstraint,
    DateTime,
    ForeignKey,
    String,
    UniqueConstraint,
    Index,
    func,
)
from sqlalchemy.dialects.postgresql import UUID as PostgreSQLUUID
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, relationship, mapped_column

from db.entity.base import EntityBase as Base

if TYPE_CHECKING:
    from db.entity.task_entity import Task


def gen_random_uuid() -> UUID:
    """Generate a random UUID v4 for database default."""
    return uuid4()


def now_utc() -> datetime:
    """Get current UTC datetime."""
    return datetime.now(timezone.utc)


class TaskDependency(Base):
    """Task Dependency entity for task relationships.

    This table stores parent-child relationships between tasks,
    allowing for complex task workflows and dependency chains.

    Table: task_dependencies
    """

    __tablename__ = "task_dependencies"

    id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        primary_key=True,
        default=gen_random_uuid,
        server_default=func.gen_random_uuid(),
    )
    """Primary key - UUID v4 generated by PostgreSQL."""

    parent_task_id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        ForeignKey("tasks.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    """Foreign key reference to the parent task."""

    child_task_id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        ForeignKey("tasks.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    """Foreign key reference to the child task."""

    dependency_type: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        default="sequential",
        server_default="sequential",
    )
    """Type of dependency: 'sequential', 'parallel', 'conditional'."""

    condition_json: Mapped[Optional[dict]] = mapped_column(
        JSONB,
        nullable=True,
    )
    """Optional condition for conditional dependencies (JSON format)."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=now_utc,
        server_default=func.now(),
    )
    """Record creation timestamp (UTC)."""

    # Relationships
    parent_task: Mapped["Task"] = relationship(
        "Task",
        foreign_keys=[parent_task_id],
        back_populates="child_dependencies",
    )
    """The parent task in this dependency."""

    child_task: Mapped["Task"] = relationship(
        "Task",
        foreign_keys=[child_task_id],
        back_populates="parent_dependencies",
    )
    """The child task in this dependency."""

    __table_args__ = (
        UniqueConstraint('parent_task_id', 'child_task_id', name='uq_task_dependencies_parent_child'),
        CheckConstraint(
            "parent_task_id != child_task_id",
            name='ck_task_dependencies_no_self_reference'
        ),
        Index("idx_deps_parent", "parent_task_id"),
        Index("idx_deps_child", "child_task_id"),
        {"extend_existing": True},
    )

    def __repr__(self) -> str:
        return f"<TaskDependency(id={self.id}, parent={self.parent_task_id}, child={self.child_task_id}, type={self.dependency_type})>"
