# pyright: reportMissingImports=false
"""
SQLAlchemy entity models for tasks and task dependencies.

This module defines the database entities for task management including
task tracking, scheduling, and parent-child task relationships.
Mirrors the original schema from db/schema/tasks.py and db/schema/task_dependencies.py.

Import path: db.entity.task_entity
"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import TYPE_CHECKING, Any, Optional
from uuid import UUID, uuid4

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID as PostgreSQLUUID
from sqlalchemy.orm import Mapped, mapped_column

from db.entity.base import EntityBase as Base
from db.types import TaskStatus, Priority, DependencyType


def gen_random_uuid() -> UUID:
    """Generate a random UUID v4 for database default."""
    return uuid4()


def now_utc() -> datetime:
    """Get current UTC datetime."""
    return datetime.now(timezone.utc)


class Task(Base):
    """Task entity for tracking agent tasks and their execution.
    
    This table stores task definitions, execution status, and results.
    Tasks can have parent-child relationships for hierarchical task decomposition.
    The session_id field links to LangGraph thread_id for checkpoint integration.
    
    Table: tasks
    """
    
    __tablename__ = "tasks"
    
    id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        primary_key=True,
        default=gen_random_uuid,
        server_default=func.gen_random_uuid(),
    )
    """Primary key - UUID v4 generated by PostgreSQL."""
    
    user_id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=False,  # We'll create a custom index below
    )
    """Foreign key reference to the owning user (CASCADE delete)."""
    
    agent_id: Mapped[Optional[UUID]] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        ForeignKey("agent_instances.id", ondelete="SET NULL"),
        nullable=True,
        index=False,  # We'll create a custom index below
    )
    """Foreign key reference to the executing agent instance (SET NULL on delete)."""
    
    session_id: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
    )
    """LangGraph thread_id for checkpoint integration and session tracking."""
    
    parent_task_id: Mapped[Optional[UUID]] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        ForeignKey("tasks.id", ondelete="CASCADE"),
        nullable=True,
        index=True,
    )
    """Self-referencing foreign key for parent-child task relationships (CASCADE delete)."""
    
    task_type: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )
    """Type of task (e.g., 'research', 'analysis', 'code_generation')."""
    
    status: Mapped[TaskStatus] = mapped_column(
        String(50),
        nullable=False,
        default=TaskStatus.pending,
        server_default=TaskStatus.pending.value,
    )
    """Current execution status of the task."""
    
    priority: Mapped[Priority] = mapped_column(
        String(50),
        nullable=False,
        default=Priority.normal,
        server_default=Priority.normal.value,
    )
    """Task priority level for scheduling."""
    
    payload: Mapped[Optional[dict[str, Any]]] = mapped_column(
        JSONB,
        nullable=True,
    )
    """JSONB field for task specifications and input parameters."""
    
    result: Mapped[Optional[dict[str, Any]]] = mapped_column(
        JSONB,
        nullable=True,
    )
    """JSONB field for task execution results and output."""
    
    error_message: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
    )
    """Error message if task execution failed."""
    
    retry_count: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
        server_default="0",
    )
    """Number of retry attempts made for this task."""
    
    max_retries: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=3,
        server_default="3",
    )
    """Maximum number of retry attempts allowed."""
    
    scheduled_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        index=True,
    )
    """Scheduled execution timestamp for temporal scheduling."""
    
    started_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )
    """Task execution start timestamp."""
    
    completed_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )
    """Task completion timestamp (success or failure)."""
    
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=now_utc,
        server_default=func.now(),
    )
    """Record creation timestamp (UTC)."""
    
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=now_utc,
        server_default=func.now(),
        onupdate=now_utc,
    )
    """Last update timestamp (UTC)."""
    
    __table_args__ = (
        CheckConstraint(
            "status IN ('pending', 'running', 'completed', 'failed', 'cancelled')",
            name="ck_tasks_status",
        ),
        CheckConstraint(
            "priority IN ('low', 'normal', 'high', 'critical')",
            name="ck_tasks_priority",
        ),
        CheckConstraint(
            "retry_count >= 0",
            name="ck_tasks_retry_count",
        ),
        CheckConstraint(
            "max_retries >= 0",
            name="ck_tasks_max_retries",
        ),
        Index("idx_tasks_status", "status", "created_at"),
        Index("idx_tasks_user", "user_id", "created_at"),
        Index("idx_tasks_agent", "agent_id", "created_at"),
        Index(
            "idx_tasks_scheduled",
            "scheduled_at",
            postgresql_where=(status == 'pending'),  # type: ignore
        ),
        {"extend_existing": True},
    )
    
    def __repr__(self) -> str:
        return f"<Task(id={self.id}, user_id={self.user_id}, task_type={self.task_type!r}, status={self.status!r})>"


class TaskDependency(Base):
    """Task dependency entity for defining relationships between tasks.
    
    This table stores dependencies between tasks using the adjacency list pattern.
    Each record defines a relationship where:
    - parent_task_id: The task that must complete first (or condition source)
    - child_task_id: The task that depends on the parent
    - dependency_type: How the tasks relate (sequential, parallel, conditional)
    - condition_json: Optional condition logic for conditional dependencies
    
    The model enforces:
    - No self-references (a task cannot depend on itself)
    - No duplicate dependencies between the same task pair
    - CASCADE delete when either parent or child task is deleted
    
    Table: task_dependencies
    """
    
    __tablename__ = "task_dependencies"
    
    id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        primary_key=True,
        default=gen_random_uuid,
        server_default=func.gen_random_uuid(),
    )
    """Primary key - UUID v4 generated by PostgreSQL."""
    
    parent_task_id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        ForeignKey("tasks.id", ondelete="CASCADE"),
        nullable=False,
        index=False,  # We'll create custom indexes below
    )
    """Foreign key to the parent task (CASCADE delete)."""
    
    child_task_id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        ForeignKey("tasks.id", ondelete="CASCADE"),
        nullable=False,
        index=False,  # We'll create custom indexes below
    )
    """Foreign key to the child task (CASCADE delete)."""
    
    dependency_type: Mapped[DependencyType] = mapped_column(
        String(50),
        nullable=False,
        default=DependencyType.sequential,
        server_default=DependencyType.sequential.value,
    )
    """Type of dependency: sequential, parallel, or conditional."""
    
    condition_json: Mapped[Optional[dict[str, Any]]] = mapped_column(
        JSONB,
        nullable=True,
    )
    """JSONB field for conditional dependency logic (if/when clauses)."""
    
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=now_utc,
        server_default=func.now(),
    )
    """Record creation timestamp (UTC)."""
    
    __table_args__ = (
        # Prevent self-referencing (task cannot depend on itself)
        CheckConstraint(
            "parent_task_id != child_task_id",
            name="ck_task_dependencies_no_self_reference",
        ),
        # Prevent duplicate dependencies between the same task pair
        UniqueConstraint(
            "parent_task_id",
            "child_task_id",
            name="uq_task_dependencies_parent_child",
        ),
        # Index for finding all dependencies of a task (as parent)
        Index("idx_deps_parent", "parent_task_id"),
        # Index for finding all tasks that depend on a task (as child)
        Index("idx_deps_child", "child_task_id"),
        {"extend_existing": True},
    )
    
    def __repr__(self) -> str:
        return (
            f"<TaskDependency(id={self.id}, "
            f"parent_task_id={self.parent_task_id}, "
            f"child_task_id={self.child_task_id}, "
            f"dependency_type={self.dependency_type!r})>"
        )


# Type checking imports for forward references
if TYPE_CHECKING:
    pass  # No forward references needed currently