# pyright: reportMissingImports=false
"""
SQLAlchemy entity model for task schedules.

This module defines the database entity for task scheduling,
including schedule types (once, interval, cron) and execution tracking.
Mirrors the original schema from db/schema/task_schedules.py.

Import path: db.entity.task_schedule_entity
"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import TYPE_CHECKING, Optional
from uuid import UUID, uuid4

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import UUID as PostgreSQLUUID
from sqlalchemy.orm import Mapped, mapped_column

from db.entity.base import EntityBase as Base
from db.types import ScheduleType


def gen_random_uuid() -> UUID:
    """Generate a random UUID v4 for database default."""
    return uuid4()


def now_utc() -> datetime:
    """Get current UTC datetime."""
    return datetime.now(timezone.utc)


class TaskSchedule(Base):
    """Task schedule entity for defining recurring task execution patterns.
    
    This table stores schedule definitions linked to task templates.
    Each task template can have at most one schedule (unique constraint).
    The schedule_type determines the format and validation rules for schedule_expression.
    next_run_at is computed by background scheduler service and can be NULL initially.
    
    Table: task_schedules
    """
    
    __tablename__ = "task_schedules"
    
    id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        primary_key=True,
        default=gen_random_uuid,
        server_default=func.gen_random_uuid(),
    )
    """Primary key - UUID v4 generated by PostgreSQL."""
    
    task_template_id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        ForeignKey("tasks.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    """Foreign key reference to the task template (CASCADE delete)."""
    
    schedule_type: Mapped[ScheduleType] = mapped_column(
        String(50),
        nullable=False,
        default=ScheduleType.cron,
        server_default=ScheduleType.cron.value,
    )
    """Type of schedule: once, interval, or cron."""
    
    schedule_expression: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )
    """Schedule expression format depends on schedule_type:
    - cron: Standard unix cron format (5 parts: minute hour day month weekday)
    - interval: ISO 8601 duration (e.g., PT1H for hourly, P1D for daily)
    - once: ISO 8601 timestamp (e.g., 2026-03-22T12:00:00Z)
    """
    
    next_run_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        index=False,  # Partial index below
    )
    """Next scheduled execution time (computed by background job, NULL until processed)."""
    
    last_run_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )
    """Last execution timestamp (updated on each schedule execution)."""
    
    is_active: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=True,
        server_default="true",
    )
    """Whether the schedule is active and should be processed."""
    
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=now_utc,
        server_default=func.now(),
    )
    """Record creation timestamp (UTC)."""
    
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=now_utc,
        server_default=func.now(),
        onupdate=now_utc,
    )
    """Last update timestamp (UTC)."""
    
    __table_args__ = (
        CheckConstraint(
            "schedule_type IN ('once', 'interval', 'cron')",
            name="ck_task_schedules_schedule_type",
        ),
        # Validation for cron format: 5 space-separated parts
        # Each part can be *, numbers, ranges, lists, or step values
        CheckConstraint(
            r"""
            CASE 
                WHEN schedule_type = 'cron' THEN
                    schedule_expression ~ '^(\*|[0-9]+(-[0-9]+)?(,[0-9]+(-[0-9]+)?)*|\*/[0-9]+)( +(\*|[0-9]+(-[0-9]+)?(,[0-9]+(-[0-9]+)?)*|\*/[0-9]+)){4}$'
                ELSE TRUE
            END
            """,
            name="ck_task_schedules_cron_format",
        ),
        # Validation for interval format: ISO 8601 duration
        # P[n]Y[n]M[n]DT[n]H[n]M[n]S or P[n]W
        CheckConstraint(
            r"""
            CASE 
                WHEN schedule_type = 'interval' THEN
                    schedule_expression ~ '^P(\d+Y)?(\d+M)?(\d+D)?(T(\d+H)?(\d+M)?(\d+S)?)?$|^P\d+W$'
                ELSE TRUE
            END
            """,
            name="ck_task_schedules_interval_format",
        ),
        # Validation for once format: ISO 8601 timestamp
        CheckConstraint(
            r"""
            CASE 
                WHEN schedule_type = 'once' THEN
                    schedule_expression ~ '^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:\d{2})$'
                ELSE TRUE
            END
            """,
            name="ck_task_schedules_once_format",
        ),
        UniqueConstraint("task_template_id", name="uq_task_schedules_template"),
        Index(
            "idx_schedules_next_run",
            "next_run_at",
            postgresql_where=func.coalesce(is_active, False) == True,
        ),
        {"extend_existing": True},
    )
    
    def __repr__(self) -> str:
        return f"<TaskSchedule(id={self.id}, task_template_id={self.task_template_id}, schedule_type={self.schedule_type!r}, is_active={self.is_active})>"


# Type checking imports for forward references
if TYPE_CHECKING:
    pass  # No forward references needed currently