# pyright: reportMissingImports=false, reportUndefinedVariable=false
"""
SQLAlchemy entity model for tool calls.

This module defines the database entity for tracking tool call executions.
Tool calls link tasks to tools and capture input/output data for each invocation.
Mirrors the original schema from db/schema/tool_calls.py.

Import path: db.entity.tool_call_entity
"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import TYPE_CHECKING, Any, Optional
from uuid import UUID, uuid4

from sqlalchemy import (
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID as PostgreSQLUUID
from sqlalchemy.orm import Mapped, mapped_column

from db.entity.base import EntityBase as Base


def gen_random_uuid() -> UUID:
    """Generate a random UUID v4 for database default."""
    return uuid4()


def now_utc() -> datetime:
    """Get current UTC datetime."""
    return datetime.now(timezone.utc)


class ToolCall(Base):
    """ToolCall entity for tracking tool invocations.
    
    This table stores records of tool calls made during task execution.
    Each tool call links a task to a specific tool and version,
    capturing input parameters, output results, execution status, and performance metrics.
    
    Table: tool_calls
    """
    
    __tablename__ = "tool_calls"
    
    id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        primary_key=True,
        default=gen_random_uuid,
        server_default=func.gen_random_uuid(),
    )
    """Primary key - UUID v4 generated by PostgreSQL."""
    
    task_id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        ForeignKey("tasks.id", ondelete="CASCADE"),
        nullable=False,
        index=False,  # We'll create a custom index below
    )
    """Foreign key reference to the task that made this tool call (CASCADE delete)."""
    
    tool_id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        ForeignKey("tools.id", ondelete="CASCADE"),
        nullable=False,
        index=False,  # We'll create a custom index below
    )
    """Foreign key reference to the tool that was called (CASCADE delete)."""
    
    tool_version_id: Mapped[Optional[UUID]] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        ForeignKey("tool_versions.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    """Foreign key reference to the specific tool version used (SET NULL on delete)."""
    
    input: Mapped[Optional[dict[str, Any]]] = mapped_column(
        JSONB,
        nullable=True,
    )
    """JSONB field for tool call input parameters."""
    
    output: Mapped[Optional[dict[str, Any]]] = mapped_column(
        JSONB,
        nullable=True,
    )
    """JSONB field for tool call output/results. Note: Large binary data should use external storage."""
    
    status: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        default="pending",
        server_default="pending",
    )
    """Execution status of the tool call (pending, running, completed, failed)."""
    
    error_message: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
    )
    """Error message if tool call execution failed."""
    
    duration_ms: Mapped[Optional[int]] = mapped_column(
        Integer,
        nullable=True,
    )
    """Execution duration in milliseconds."""
    
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=now_utc,
        server_default=func.now(),
    )
    """Record creation timestamp (UTC)."""
    
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=now_utc,
        server_default=func.now(),
        onupdate=now_utc,
    )
    """Last update timestamp (UTC)."""
    
    __table_args__ = (
        CheckConstraint(
            "status IN ('pending', 'running', 'completed', 'failed')",
            name="ck_tool_calls_status",
        ),
        CheckConstraint(
            "duration_ms >= 0",
            name="ck_tool_calls_duration_ms",
        ),
        Index("idx_tool_calls_task", "task_id"),
        Index("idx_tool_calls_tool", "tool_id"),
        {"extend_existing": True},
    )
    
    def __repr__(self) -> str:
        return f"<ToolCall(id={self.id}, task_id={self.task_id}, tool_id={self.tool_id}, status={self.status!r})>"


# Type checking imports for forward references
if TYPE_CHECKING:
    pass  # No forward references needed currently