# pyright: reportMissingImports=false, reportUndefinedVariable=false
"""
SQLAlchemy entity models for users and API keys.

This module defines the database entities for user management and API key authentication.
Mirrors the original schema from db/schema/users.py.
"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import TYPE_CHECKING, Optional
from uuid import UUID, uuid4

from sqlalchemy import (
    Boolean,
    DateTime,
    ForeignKey,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import UUID as PostgreSQLUUID
from sqlalchemy.orm import Mapped, relationship, mapped_column

from db.entity.base import EntityBase as Base


def gen_random_uuid() -> UUID:
    """Generate a random UUID v4 for database default."""
    return uuid4()


def now_utc() -> datetime:
    """Get current UTC datetime."""
    return datetime.now(timezone.utc)


class User(Base):
    """User entity for authentication and authorization.
    
    This table stores user account information with unique constraints
    on username and email to prevent duplicates.
    
    Table: users
    """
    
    __tablename__ = "users"
    
    id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        primary_key=True,
        default=gen_random_uuid,
        server_default=func.gen_random_uuid(),
    )
    """Primary key - UUID v4 generated by PostgreSQL."""
    
    username: Mapped[str] = mapped_column(
        Text,
        unique=True,
        nullable=False,
        index=True,
    )
    """Unique username for login and identification."""
    
    email: Mapped[str] = mapped_column(
        Text,
        unique=True,
        nullable=False,
        index=True,
    )
    """Unique email address for communication and recovery."""
    
    is_active: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=True,
        server_default="true",
    )
    """Whether the user account is active."""
    
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=now_utc,
        server_default=func.now(),
    )
    """Record creation timestamp (UTC)."""
    
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=now_utc,
        server_default=func.now(),
        onupdate=now_utc,
    )
    """Last update timestamp (UTC)."""
    
    # Relationship to API keys
    api_keys: Mapped[list["APIKey"]] = relationship(
        "APIKey",
        back_populates="user",
        cascade="all, delete-orphan",
    )
    """API keys associated with this user."""
    
    # Relationship to LLM endpoint groups
    llm_endpoint_groups: Mapped[list["LLMEndpointGroup"]] = relationship(
        "LLMEndpointGroup",
        back_populates="user",
        cascade="all, delete-orphan",
    )
    """LLM endpoint groups associated with this user."""
    
    # Relationship to LLM endpoints
    llm_endpoints: Mapped[list["LLMEndpoint"]] = relationship(
        "LLMEndpoint",
        back_populates="user",
        cascade="all, delete-orphan",
    )
    """LLM endpoints associated with this user."""
    
    # Note: Relationships to other entities (agent_instances, tasks, etc.)
    # are defined in their respective entity files using string references
    # to avoid circular imports.
    
    __table_args__ = (
        UniqueConstraint("username", name="uq_users_username"),
        UniqueConstraint("email", name="uq_users_email"),
        {"extend_existing": True},
    )
    
    def __repr__(self) -> str:
        return f"<User(id={self.id}, username={self.username!r}, email={self.email!r})>"


class APIKey(Base):
    """API key entity for authentication.
    
    This table stores hashed API keys for user authentication.
    Keys should never be stored in plain text - only the hash is persisted.
    Foreign key to users with cascade delete to prevent orphaned keys.
    
    Table: api_keys
    """
    
    __tablename__ = "api_keys"
    
    id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        primary_key=True,
        default=gen_random_uuid,
        server_default=func.gen_random_uuid(),
    )
    """Primary key - UUID v4 generated by PostgreSQL."""
    
    user_id: Mapped[UUID] = mapped_column(
        PostgreSQLUUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    """Foreign key reference to the owning user."""
    
    key_hash: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )
    """Hashed API key value - never store plain text keys."""
    
    name: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
    )
    """Optional human-readable name for the key."""
    
    last_used_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )
    """Last time this key was used for authentication."""
    
    expires_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )
    """Optional expiration timestamp for the key."""
    
    is_active: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=True,
        server_default="true",
    )
    """Whether the API key is currently active."""
    
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=now_utc,
        server_default=func.now(),
    )
    """Record creation timestamp (UTC)."""
    
    # Relationship to user
    user: Mapped["User"] = relationship(
        "User",
        back_populates="api_keys",
    )
    """The user who owns this API key."""
    
    __table_args__ = (
        {"extend_existing": True},
    )
    
    def __repr__(self) -> str:
        return f"<APIKey(id={self.id}, user_id={self.user_id}, name={self.name!r})>"


# Type checking imports for forward references
if TYPE_CHECKING:
    from db.entity.llm_endpoint_entity import LLMEndpoint, LLMEndpointGroup